const API_URL = (() => {
        const e = window.location.hostname;
        if ("localhost" === e || "127.0.0.1" === e || "" === e) return "/data.json";
        const a = "https://YOUR_R2_DOMAIN/data.json";
        return a.includes("YOUR_R2_DOMAIN") ? "/data.json" : a;
    })(),
    INFRA_URL = API_URL.replace(/data\.json$/, "infrastructure.json"),
    LIVE_URL = API_URL.replace(/data\.json$/, "live.json"),
    TRAINS_BASE_URL = API_URL.replace(/data\.json$/, "trains/"),
    STATIONS_BASE_URL = API_URL.replace(/data\.json$/, "stations/"),
    STATION_TO_GERENCIA_URL = API_URL.replace(/data\.json$/, "station-to-gerencia.json"),
    LINE_COLORS = {
        Mitre: "#5f8751",
        Sarmiento: "#89a0b9",
        Roca: "#3f6596",
        "Belgrano Sur": "#fdc849",
        "Belgrano Norte": "#a4252c",
        "San MartÃ­n": "#cd5055",
        Urquiza: "#da6c2b",
        "Tren de la Costa": "#9b89b3",
    },
    DEFAULT_LINE_COLOR = "#0077C8",
    STATIC_ONLY_GERENCIA_IDS = [],
    NO_LIVE_DATA_COPY = {
        61: "Datos en vivo no disponibles â€” se muestran alertas de servicio cuando el operador las publica.",
    };
function isStaticOnlyGerencia(e) {
    return null != e && STATIC_ONLY_GERENCIA_IDS.includes(Number(e));
}
function noLiveDataCopy(e) {
    return null == e ? null : NO_LIVE_DATA_COPY[Number(e)] || null;
}
const STATION_DISPLAY_NAMES = { "Ing. PP. MarÃ­n": "Ing. P. MarÃ­n" },
    STATION_CONTEXT_STRIP_PARENS = ["Retiro (LGM)", "Retiro (LSM)", "Retiro (BN)"],
    STATION_SEO_NAMES = {
        "Retiro (LGM)": [
            "Terminal Retiro LÃ­nea General Mitre",
            "Retiro LÃ­nea Mitre",
            "Retiro General Mitre",
            "Retiro Mitre",
        ],
        "Retiro (LSM)": ["Terminal Retiro LÃ­nea San MartÃ­n", "Retiro LÃ­nea San MartÃ­n", "Retiro San MartÃ­n"],
        "Retiro (BN)": [
            "Terminal Retiro LÃ­nea Belgrano Norte",
            "Retiro LÃ­nea Belgrano Norte",
            "Retiro Belgrano Norte",
        ],
    },
    STATION_SHORT_NAMES = {
        "Hospital San Juan de Dios": "Hosp. SJ de Dios",
        "Marinos C. G Belgrano": "M. C. G. Belgrano",
        "SÃ¡nchez de Mendeville": "S. de Mendeville",
        "Apeadero Kloosterman": "Ap. Kloosterman",
        "Hospital Cuenca Alta": "Hosp. Cuenca Alta",
        "Lisandro de la Torre": "L. de la Torre",
        "Marinos del Fournier": "M. del Fournier",
        "Remedios de Escalada": "R. de Escalada",
        "Dr. A. SÃ¡enz  Prov.": "Dr. SÃ¡enz Prov.",
        "Dr. A. SÃ¡enz Viad.": "Dr. SÃ¡enz Viad.",
        "SantillÃ¡n y Kosteki": "SantillÃ¡n y K.",
        "Canal San Fernando": "C. San Fernando",
        "Ingeniero S. Brian": "Ing. S. Brian",
        "Lezica y Torrezuri": "Lezica y T.",
        "Capilla del SeÃ±or": "Cap. del SeÃ±or",
        "Carlos Spegazzini": "C. Spegazzini",
        "Dr. Ing. Castello": "Dr. Castello",
        "HipÃ³lito Yrigoyen": "H. Yrigoyen",
        "Maquinista R. Cal": "Maq. R. Cal",
        "Ministro Carranza": "Min. Carranza",
        "Pte. Arturo Illia": "Pte. A. Illia",
        "UniÃ³n Ferroviaria": "U. Ferroviaria",
        "Alejandro PetiÃ³n": "A. PetiÃ³n",
        "Florencio Varela": "F. Varela",
        "Hospital EspaÃ±ol": "Hosp. EspaÃ±ol",
        "MarÃ­a Eva Duarte": "M. E. Duarte",
        "Villa del Parque": "V. del Parque",
    },
    STATION_SLUG_ALIASES = {
        "retiro-mitre": "retiro-lgm",
        "retiro-sm": "retiro-lsm",
        "retiro-san-martin": "retiro-lsm",
        "retiro-bn": "retiro-bn",
    },
    STATION_DISPLAY_SLUGS = { "retiro-lgm": "retiro-mitre", "retiro-lsm": "retiro-sm" },
    LINE_ABBREVIATIONS = {
        Mitre: "MI",
        Sarmiento: "SA",
        Roca: "RO",
        "Belgrano Sur": "BS",
        "Belgrano Norte": "BN",
        "San MartÃ­n": "SM",
        Urquiza: "UR",
        "Tren de la Costa": "TC",
    },
    TERMINAL_STATIONS = [
        "Maipú",
        "Delta",
        "Retiro",
        "Retiro (LGM)",
        "Tigre",
        "Bartolomé Mitre",
        "José León Suárez",
        "Victoria",
        "Capilla del Señor",
        "Villa Ballester",
        "Zárate",
        "Retiro (BN)",
        "Villa Rosa",
        "Grand Bourg",
        "Boulogne Sur Mer",
        "Federico Lacroze",
        "General Lemos",
        "Retiro (LSM)",
        "Dr. Cabred",
        "José C. Paz",
        "Pilar",
        "Once",
        "Moreno",
        "Mercedes",
        "Merlo",
        "Lobos",
        "Las Heras",
        "Luján",
        "Dr. A. Sáenz Viad.",
        "González Catán",
        "Tapiales",
        "Marinos C. G Belgrano",
        "Lozano",
        "Constitución",
        "Alejandro Korn",
        "Glew",
        "Cañuelas",
        "La Plata",
        "Bosques",
        "Chascomús",
        "Ezeiza",
        "Monte",
        "Lobos",
        "J. M. Gutiérrez",
        "Temperley",
        "Haedo",
        "Remedios de Escalada",
        "Hospital San Juan de Dios",
    ],
    UI_CONSTANTS = {
        MAX_PAST_STATIONS_BEFORE_COLLAPSE: 3,
        TERMINAL_THRESHOLD_OUTBOUND: 5,
        TERMINAL_THRESHOLD_INBOUND: 95,
        REFRESH_DEBOUNCE_MS: 1e3,
        SHOW_DEBUG_INFO: !1,
        COLORS: {
            TRAIN_BODY_AT_STATION: "#0077C8",
            TRAIN_BODY_MOVING: "#5CA9E5",
            TRAIN_WINDSHIELD: "#2C3E50",
            TRAIN_LOWER_PANEL: "#FFFFFF",
        },
        SVG_DIAGRAM: {
            WIDTH: 500,
            STATION_SPACING: 80,
            PADDING_TOP: 50,
            PADDING_BOTTOM: 50,
            LEFT_TRACK_X: 80,
            RIGHT_TRACK_X: 420,
            TERMINAL_DOT_RADIUS: 10,
            TRANSFER_DOT_RADIUS: 8,
            STATION_DOT_RADIUS: 6,
            STATION_DOT_STROKE_WIDTH: 3,
            TERMINAL_STROKE_COLOR: "#0077C8",
            TRANSFER_STROKE_COLOR: "#5CA9E5",
            MAX_STATION_NAME_LENGTH: 35,
            TRAIN_ICON_SCALE: 0.6,
            MOBILE_SPACING_SCALE: 0.7,
            MOBILE_MIN_SPACING: 30,
            ADAPTIVE_SPACING: {
                SMALL_ROUTE_MAX: 15,
                MEDIUM_ROUTE_MAX: 25,
                SPACING_LARGE: 60,
                SPACING_MEDIUM: 50,
                SPACING_SMALL: 40,
            },
        },
    },
    CONNECTED_ROUTES = {
        "constitucion-ezeiza": {
            continuesTo: {
                slug: "ezeiza-canuelas",
                name: "Ezeiza - Cañuelas",
                transferStation: "Ezeiza",
                note: "Transferir en Ezeiza",
            },
        },
        "ezeiza-canuelas": {
            continuesTo: {
                slug: "constitucion-ezeiza",
                name: "Constitución - Ezeiza",
                transferStation: "Ezeiza",
                note: "Transferir en Ezeiza",
            },
        },
        "constitucion-bosques-via-quilmes": {
            continuesTo: {
                slug: "constitucion-bosques",
                name: "Ver circuito completo",
                label: "",
                note: "VÃ­a Quilmes + VÃ­a Temperley",
            },
        },
        "constitucion-bosques-via-temperley": {
            continuesTo: {
                slug: "constitucion-bosques",
                name: "Ver circuito completo",
                label: "",
                note: "VÃ­a Quilmes + VÃ­a Temperley",
            },
        },
        "bosques-gutierrez": {
            continuesTo: {
                slug: "constitucion-bosques",
                name: "Circuito Constitución - Bosques",
                label: "Conecta con:",
                note: "En Bosques",
            },
        },
    },
    LOOP_SERVICES = {
        "bosques-via-quilmes": {
            id: "bosques-via-quilmes",
            nombre: "Constitución - Bosques (Circuito por VÃ­a Quilmes)",
            nombreCorto: "Circuito por VÃ­a Quilmes",
            gerencia: "Roca",
            gerenciaSlug: "roca",
            firstBranch: "quilmes",
            components: [
                { ramalId: 13, direction: "outbound", slug: "constitucion-bosques-via-quilmes" },
                { ramalId: 15, direction: "inbound", slug: "constitucion-bosques-via-temperley" },
            ],
            loopPoint: "bosques",
            terminal: "constitucion",
            stations: [
                "constitucion",
                "santillan-y-kosteki",
                "sarandi",
                "villa-dominico",
                "wilde",
                "don-bosco",
                "bernal",
                "quilmes",
                "ezpeleta",
                "berazategui",
                "villa-espana",
                "ranelagh",
                "sourigues",
                "bosques",
                "zeballos",
                "florencio-varela",
                "dante-ardigo",
                "claypole",
                "rafael-calzada",
                "jose-marmol",
                "temperley",
                "lomas-de-zamora",
                "banfield",
                "remedios-de-escalada",
                "lanus",
                "gerli",
                "santillan-y-kosteki",
                "hipolito-yrigoyen",
            ],
            branchBoundary: { quilmesBranchEnd: 13, temperleyBranchStart: 14 },
        },
        "bosques-via-temperley": {
            id: "bosques-via-temperley",
            nombre: "Constitución - Bosques (Circuito por VÃ­a Temperley)",
            nombreCorto: "Circuito por VÃ­a Temperley",
            gerencia: "Roca",
            gerenciaSlug: "roca",
            firstBranch: "temperley",
            components: [
                { ramalId: 15, direction: "outbound", slug: "constitucion-bosques-via-temperley" },
                { ramalId: 13, direction: "inbound", slug: "constitucion-bosques-via-quilmes" },
            ],
            loopPoint: "bosques",
            terminal: "constitucion",
            stations: [
                "constitucion",
                "hipolito-yrigoyen",
                "santillan-y-kosteki",
                "gerli",
                "lanus",
                "remedios-de-escalada",
                "banfield",
                "lomas-de-zamora",
                "temperley",
                "jose-marmol",
                "rafael-calzada",
                "claypole",
                "dante-ardigo",
                "florencio-varela",
                "zeballos",
                "bosques",
                "sourigues",
                "ranelagh",
                "villa-espana",
                "berazategui",
                "ezpeleta",
                "quilmes",
                "bernal",
                "don-bosco",
                "wilde",
                "villa-dominico",
                "sarandi",
                "santillan-y-kosteki",
            ],
            branchBoundary: { temperleyBranchEnd: 15, quilmesBranchStart: 16 },
        },
    },
    BOSQUES_LOOP = {
        slug: "constitucion-bosques",
        nombre: "Constitución - Bosques",
        nombreCorto: "Circuito Bosques",
        gerencia: "Roca",
        gerenciaSlug: "roca",
        componentRamales: [13, 15],
        componentSlugs: ["constitucion-bosques-via-quilmes", "constitucion-bosques-via-temperley"],
        diagrams: {
            left: {
                id: "via-quilmes",
                title: "VÃ­a Quilmes (Horario)",
                direction: "clockwise",
                loopService: "bosques-via-quilmes",
            },
            right: {
                id: "via-temperley",
                title: "VÃ­a Temperley (Antihorario)",
                direction: "counterclockwise",
                loopService: "bosques-via-temperley",
            },
        },
        loopPoint: "bosques",
        terminal: "constitucion",
    },
    ACCESSIBILITY_ICONS = {
        wheelchair_accessible: { icon: "â™¿", label: "Acceso para sillas de ruedas" },
        elevator: { icon: "ðŸ›—", label: "Ascensor" },
        tactile_path: { icon: "ðŸ¦¯", label: "Camino táctil" },
        accessible_restroom: { icon: "ðŸš»", label: "Baño accesible" },
    },
    FACILITY_ICONS = {
        restrooms: { icon: "ðŸš»", label: "Baños" },
        cajero: { icon: "ðŸ’³", label: "Cajero automático" },
        cafe: { icon: "â˜•", label: "CafeterÃ­a" },
        kiosk: { icon: "ðŸª", label: "Kiosco" },
        parking: { icon: "ðŸ…¿ï¸", label: "Estacionamiento" },
        bike_parking: { icon: "ðŸš²", label: "Bicicletero" },
        covered_waiting: { icon: "ðŸ ", label: "Sala de espera cubierta" },
        ticket_office: { icon: "ðŸŽ«", label: "BoleterÃ­a" },
        sube_recharge: { icon: "ðŸš‡", label: "Carga SUBE" },
    },
    LANDMARK_ICONS = {
        stadium: "ðŸŸï¸",
        venue: "ðŸŽ­",
        museum: "ðŸ›ï¸",
        hospital: "ðŸ¥",
        university: "ðŸŽ“",
        school: "ðŸ«",
        shopping: "ðŸ›’",
        park: "ðŸŒ³",
        government: "ðŸ›ï¸",
        tourist: "ðŸ“¸",
        bus_station: "ðŸšŒ",
        subway: "ðŸš‡",
        train_station: "ðŸš‰",
        transport: "ðŸšŒ",
        bike_share: "ðŸš²",
    };
